import type { Metadata } from "next";
import { Inter } from "next/font/google"; // For Google Fonts if needed
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gilroy = 'https://fonts.cdnfonts.com/css/gilroy-bold';
const sora = 'https://fonts.cdnfonts.com/css/sora-3';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Include the font links from the CDN */}
      <head>
        <link rel="stylesheet" href={gilroy} />
        <link rel="stylesheet" href={sora} />
      </head>
      <body className={inter.className}>
        {children
        }</body>
    </html>
  );
}
